### ISSUE TITLE
Scope

### ISSUE THREAD

**Issue by g4s8** [artipie/debian-adapter#42]
Scope of work for Debian adapter:
 - [x] SHA256 support for release index file https://github.com/artipie/debian-adapter/issues/41
 - [x] GPG clearsign signature for index files https://github.com/artipie/debian-adapter/issues/29
 - [x] Support Release files https://github.com/artipie/debian-adapter/issues/28
 - [ ] `all` architecture support #24
 - [x] Create/update Packages files scope/adapter #11
 - [x] Batch update for multiple packages #51
